/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "templates/**/*.twig",
    "components/**/*.twig",
    "tw_tws.theme",
    "../../../modules/custom/**/templates/*.twig"
  ],
  safelist: [
    'w-28','mt-16', 'mx-10', 'mt-9', 'form-select',
    'form-input',
    'w-full',
    'rounded-md',
    'border',
    'border-gray-300',
    'focus:border-yellow-500',
    'focus:ring-yellow-500',
    'text-gray-700',
    'text-base',
    'p-2.5',
    'checkbox',
    'text-yellow-500',
    'btn',
    'btn-warning',
    'hover:login-btn',
    'active:login-btn',
    'text-white',
    'capitalize',
    'text-lg',
    'hover:translate-y-0.5',
    'submitBtn',
    // ⬇️ Add these
    'p-6',
    'bg-white',
    'shadow-md',
    'rounded-lg',
    'max-w-md',
    'mx-auto',
    'mt-10',
    'text-2xl',
    'font-semibold',
    'mb-6',
    'text-center',
    'space-y-5',
    'px-4',
    'py-2',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-400',
    'bg-blue-600',
    'hover:bg-blue-700',
    'transition',
    'form-input', 'form-select', 'w-full', 'rounded-md', 'border', 'border-gray-300',
    'focus:border-yellow-500', 'focus:ring-yellow-500', 'text-gray-700', 'text-base', 'p-2.5',
    'bg-yellow-500', 'hover:bg-yellow-600', 'text-white', 'font-semibold',
    'py-2', 'px-4', 'rounded', 'transition-all'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Open Sans", "system-ui", "sans-serif"],
        nevis: ["Nevis", "sans-serif"],
        "nevis-bold": ["Nevis Bold", "sans-serif"],
      },
      colors: {
        gray83: "rgb(83 83 83)",
      },
    },
  },
  plugins: [],
};
